local addonName, addon = ...
local table_insert = table.insert

local achievements = {
  {
    achId = "GF001",
    title = "Guild First: Reach Level 70",
    level = nil,
    tooltip = "You were the first in your guild to reach level 70.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "Level70",
    awardMode = "solo",
    requireSameGuild = true,
  }, {
    achId = "GF002",
    title = "Guild First: Complete the Meta Achievement 'The Ambassador'",
    level = nil,
    tooltip = "You were the first in your guild to complete the Meta Achievement 'The Ambassador'.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "CoreRepMeta",
    awardMode = "solo",
    requireSameGuild = true,
  }, {
    achId = "GF003",
    title = "Guild First: Complete the Meta Achievement 'The Heroic Dungeon Master'",
    level = nil,
    tooltip = "You were the first in your guild to complete the Meta Achievement 'The Heroic Dungeon Master'.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "HeroicDungeonMeta",
    awardMode = "solo",
    requireSameGuild = true,
  }, {
    achId = "GF004",
    title = "Guild First: Complete the Meta Achievement 'The Raider'",
    level = nil,
    tooltip = "You were the first in your guild to complete the Meta Achievement 'The Raider'.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "RaidMeta",
    awardMode = "solo",
    requireSameGuild = true,
  }, {
    achId = "GF005",
    title = "Guild First: Complete the Meta Achievement 'The Scholar'",
    level = nil,
    tooltip = "You were the first in your guild to complete the Meta Achievement 'The Scholar'.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "SecoProfMeta",
    awardMode = "solo",
    requireSameGuild = true,
  }, {
    achId = "GF006",
    title = "Guild First: Complete the Meta Achievement 'The Dungeon Master'",
    level = nil,
    tooltip = "You were the first in your guild to complete the Meta Achievement 'The Dungeon Master'.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "DungeonMeta",
    awardMode = "solo",
    requireSameGuild = true,
  }, {
    achId = "GF007",
    title = "Guild First: Complete the Meta Achievement 'Metalomaniac'",
    level = nil,
    tooltip = "You were the first in your guild to complete the Meta Achievement 'Metalomaniac'.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "Meta",
    awardMode = "solo",
    requireSameGuild = true,
  }, {
    achId = "GF008",
    title = "Guild First: Complete the Meta Achievement 'The Diplomat'",
    level = nil,
    tooltip = "You were the first in your guild to complete the Meta Achievement 'The Diplomat'.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "QuestMeta",
    awardMode = "solo",
    requireSameGuild = true,
  }, {
    achId = "GF101",
    title = "Guild First: Heroic Hellfire Ramparts",
    level = nil,
    tooltip = "You were the first in your guild to complete Heroic Hellfire Ramparts.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "HRAMPARTS",
    awardMode = "party",
    requireSameGuild = true,
  }, {
    achId = "GF102",
    title = "Guild First: Heroic Blood Furnace",
    level = nil,
    tooltip = "You were the first in your guild to complete Heroic Blood Furnace.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "HBLOODFURNACE",
    awardMode = "party",
    requireSameGuild = true,
  }, {
    achId = "GF103",
    title = "Guild First: Heroic Slave Pens",
    level = nil,
    tooltip = "You were the first in your guild to complete Heroic Slave Pens.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "HSLAVEPENS",
    awardMode = "party",
    requireSameGuild = true,
  }, {
    achId = "GF104",
    title = "Guild First: Heroic Underbog",
    level = nil,
    tooltip = "You were the first in your guild to complete Heroic Underbog.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "HUNDERBOG",
    awardMode = "party",
    requireSameGuild = true,
  }, {
    achId = "GF105",
    title = "Guild First: Heroic Mana-Tombs",
    level = nil,
    tooltip = "You were the first in your guild to complete Heroic Mana-Tombs.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "HMANATOMBS",
    awardMode = "party",
    requireSameGuild = true,
  }, {
    achId = "GF106",
    title = "Guild First: Heroic Auchenai Crypts",
    level = nil,
    tooltip = "You were the first in your guild to complete Heroic Auchenai Crypts.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "HAC",
    awardMode = "party",
    requireSameGuild = true,
  }, {
    achId = "GF107",
    title = "Guild First: Heroic Old Hillsbrad Foothills",
    level = nil,
    tooltip = "You were the first in your guild to complete Heroic Old Hillsbrad Foothills.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "HOLDHILLS",
    awardMode = "party",
    requireSameGuild = true,
  }, {
    achId = "GF108",
    title = "Guild First: Heroic Sethekk Halls",
    level = nil,
    tooltip = "You were the first in your guild to complete Heroic Sethekk Halls.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "HSETHEKK",
    awardMode = "party",
    requireSameGuild = true,
  }, {
    achId = "GF109",
    title = "Guild First: Heroic The Black Morass",
    level = nil,
    tooltip = "You were the first in your guild to complete Heroic The Black Morass.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "HBLACKMORASS",
    awardMode = "party",
    requireSameGuild = true,
  }, {
    achId = "GF110",
    title = "Guild First: Heroic The Mechanar",
    level = nil,
    tooltip = "You were the first in your guild to complete Heroic The Mechanar.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "HMECHANAR",
    awardMode = "party",
    requireSameGuild = true,
  }, {
    achId = "GF111",
    title = "Guild First: Heroic Shattered Halls",
    level = nil,
    tooltip = "You were the first in your guild to complete Heroic Shattered Halls.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "HSHATTEREDHALLS",
    awardMode = "party",
    requireSameGuild = true,
  }, {
    achId = "GF112",
    title = "Guild First: Heroic Shadow Labyrinth",
    level = nil,
    tooltip = "You were the first in your guild to complete Heroic Shadow Labyrinth.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "HSLABS",
    awardMode = "party",
    requireSameGuild = true,
  }, {
    achId = "GF113",
    title = "Guild First: Heroic The Steamvault",
    level = nil,
    tooltip = "You were the first in your guild to complete Heroic The Steamvault.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "HSTEAMVAULT",
    awardMode = "party",
    requireSameGuild = true,
  }, {
    achId = "GF114",
    title = "Guild First: Heroic Botanica",
    level = nil,
    tooltip = "You were the first in your guild to complete Heroic Botanica.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "HBOTANICA",
    awardMode = "party",
    requireSameGuild = true,
  }, {
    achId = "GF115",
    title = "Guild First: Heroic Magisters' Terrace",
    level = nil,
    tooltip = "You were the first in your guild to complete Heroic Magisters' Terrace.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "HMT",
    awardMode = "party",
    requireSameGuild = true,
  }, {
    achId = "GF116",
    title = "Guild First: Heroic The Arcatraz",
    level = nil,
    tooltip = "You were the first in your guild to complete Heroic The Arcatraz.",
    icon = "Interface\\AddOns\\HardcoreAchievements\\Images\\Icons\\guild_first.png",
    points = 0,
    secret = true,
    staticPoints = true,
    hiddenUntilComplete = true,
    triggerAchievementId = "HARCATRAZ",
    awardMode = "party",
    requireSameGuild = true,
  },
}

-- Publish defs/trigger index immediately (so awarding works even if UI rows haven't been created yet).
if addon then
  addon.GuildFirst_DefById = addon.GuildFirst_DefById or {}
  addon.GuildFirst_ByTrigger = addon.GuildFirst_ByTrigger or {}
  for _, def in ipairs(achievements) do
    def.isSecret = true
    def.isGuildFirst = true
    addon.GuildFirst_DefById[def.achId] = def
    if def.triggerAchievementId then
      local k = tostring(def.triggerAchievementId)
      addon.GuildFirst_ByTrigger[k] = addon.GuildFirst_ByTrigger[k] or {}
      table_insert(addon.GuildFirst_ByTrigger[k], def.achId)
    end
  end
  addon.RegistrationQueue = addon.RegistrationQueue or {}
  local queue = addon.RegistrationQueue

  for _, def in ipairs(achievements) do
    table_insert(queue, function()
      local CreateAchievementRow = addon and addon.CreateAchievementRow
      local AchievementPanel = addon and addon.AchievementPanel
      if CreateAchievementRow and AchievementPanel then
        local row = CreateAchievementRow(
          AchievementPanel,
          def.achId,
          def.title,
          def.tooltip,
          def.icon,
          def.level,
          def.points or 0,
          nil,
          nil,
          def.staticPoints,
          def.zone,
          def
        )
        addon["GuildFirst_" .. def.achId .. "_Row"] = row
      end
    end)
  end
end

